pipeline:
  identifier: Build_adricamilo_harness_ci_example_1731530095514
  name: Build harness-ci-example
  orgIdentifier: default
  projectIdentifier: helloworld
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: adricamilo/harness-ci-example
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    connectorRef: account.harnessImage
                    image: node:16
                    shell: Sh
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    connectorRef: account.harnessImage
                    image: node:16
                    shell: Sh
                    command: npm test
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    connectorRef: account.harnessImage
                    repo: adricamilo/hello-world
                    tags:
                      - "1.0"
                    caching: true
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: minikubeexample
              namespace: hello
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
        description: ""
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: minikube
          environment:
            environmentRef: prepod
            deployToAll: false
            infrastructureDefinitions:
              - identifier: helloo
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
